apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feature-flag-api
  template:
    metadata:
      labels:
        app: feature-flag-api
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret  # Gives K8s the password so we can pull from ECR
      containers:
      - name: core-api
        image: 784079396645.dkr.ecr.us-west-2.amazonaws.com/feature-flag-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "production"
        - name: ENABLE_PREMIUM_CHECKOUT
          value: "true"
