apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - name: core-api
        image: core-api:v1
        imagePullPolicy: Never  # Tells Minikube to look for the local image we'll build next
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
