# This is part 3, version 2 .gitlab-ci.yml. 
# Must follow the blog post as the pipeline can fail without the necessary files on the repo.
stages:
  - plan
  - apply
  - build

variables:
  # Replace this with your actual ECR URI from the 'aws ecr describe-repositories' command
  FRONTEND_ECR_REPO: "<AWS-ACCOUNT-ID>.dkr.ecr.us-west-2.amazonaws.com/gitops-repo/frontend"
  AWS_REGION: "us-west-2"

terraform-plan:
  stage: plan
  tags:
    - minikube
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
      - .terraform.lock.hcl
    expire_in: 1 hour

terraform-apply:
  stage: apply
  tags:
    - minikube
  script:
    - terraform init 
    - terraform apply -auto-approve tfplan

build-frontend:
  stage: build
  tags:
    - minikube
  script:
    - echo "Logging into AWS ECR..."
    - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${FRONTEND_ECR_REPO}
    
    - echo "Building Docker Image..."
    - docker build -t ${FRONTEND_ECR_REPO}:latest -t ${FRONTEND_ECR_REPO}:${CI_COMMIT_SHORT_SHA} ./frontend
    
    - echo "Pushing Image to ECR..."
    - docker push ${FRONTEND_ECR_REPO}:latest
    - docker push ${FRONTEND_ECR_REPO}:${CI_COMMIT_SHORT_SHA}