apiVersion: v1
kind: Namespace
metadata:
  name: my-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-key-pw
      containers:
      - name: frontend
        # Make sure to use your correct ECR URI (replace the AWS Account ID)
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/gitops-repo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-apps
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort