# Separating both plan and apply stages
stages:
  - plan
  - apply

terraform-plan:
  stage: plan
  tags:
    - minikube
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
      - .terraform.lock.hcl
    expire_in: 1 hour

terraform-apply:
  stage: apply
  tags:
    - minikube
  script:
    # Terraform init + apply with auto-approve. This will run automatically without manual approval on the GitLab UI
    - terraform init 
    - terraform apply -auto-approve tfplan
