apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      imagePullSecrets:
      - name: ecr-registry-key-pw
      containers:
      - name: payment-container
        # Make sure to use your correct ECR URI (replace the AWS Account ID) 
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/gitops-repo/cart-service:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: my-apps
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80        # The port Nginx looks for (http://payment-service:80)
      targetPort: 3000