server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Routes cart-related requests
    location /api/cart {
        proxy_pass http://cart-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Routes payment-related requests
    location /api/pay {
        proxy_pass http://payment-service:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}