# ==============================================================================
# GITOPS AUTOMATION PIPELINE (for part-03  & part-04)
# ==============================================================================
# NOTE: This workflow handles the automated container builds for Part 3 and Part 4.
# GitHub Actions requires this file to reside at the absolute root of the repository
# (/.github/workflows/) to execute. Procedures will be provided on the medium blog.
# ==============================================================================

name: Build and Push to ECR (Part 3 & 4)

on:
  push:
    branches: [ "lab03" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: feature-flag-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # For part-03, comment out the lab-03/part-03 below and comment (put a #) on the lab-03/part-04 line.
          # cd lab-03/part-03/app/core-api

          # Update: point to part-04 
          cd lab-03/part-04/app/core-api
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Add a duplicate local tag named 'latest'
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

          # Push BOTH tags to Amazon ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
